import * as fs from 'fs';
import * as path from 'path';
import { URL } from 'url';
import { CertificateListItem, createDomainCertificate, listDomainCertificates } from './cert-manager';
import { TraefikSnapshot } from './traefik-api';
import { RunestoneEnv } from '../utils/env-loader';
import { RunestoneServiceRecord, toolState } from '../utils/tool-state';
import { t } from '../i18n';
import { removeDynamicConfigFile, writeDynamicConfigFile } from './dynamic-config-manager';

export interface ServiceInput {
  name: string;
  route: string;
  url: string;
  group?: string | null;
}

export interface ServiceListItem extends RunestoneServiceRecord {
  dynamicConfigExists: boolean;
}

export interface TraefikNameConflict {
  name: string;
  provider: string;
  kind: 'router' | 'service';
}

export interface TraefikHostConflict {
  name: string;
  provider: string;
  rule: string;
}

const MANAGED_CONFIG_MARKER = '# Generated by runestone service-manager.';
const namePattern = /^[a-z0-9][a-z0-9-]*$/;
const domainLabel = /^[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?$/;

function providerBaseName(name: string): string {
  return name.split('@')[0];
}

function providerName(name: string): string {
  return name.includes('@') ? name.split('@').slice(1).join('@') : 'unknown';
}

export function validateServiceName(name: string, label = t('service.label.name')): string {
  const value = name.trim();
  if (!value) {
    throw new Error(t('service.validation.required', { label }));
  }
  if (!namePattern.test(value)) {
    throw new Error(t('service.validation.nameFormat', { label }));
  }
  return value;
}

export function validateGroupName(group?: string | null): string | null {
  if (!group?.trim()) {
    return null;
  }

  const normalized = validateServiceName(group, t('service.label.group'));
  return normalized === 'none' ? null : normalized;
}

export function normalizeRouteDomain(route: string, hostDomain: string): string {
  const value = route.trim().toLowerCase();
  if (!value) {
    throw new Error(t('service.validation.routeRequired'));
  }
  if (value.includes('/') || value.includes(':')) {
    throw new Error(t('service.validation.routeNoProtocol'));
  }

  const domain = value.includes('.') ? value : `${value}.${hostDomain.toLowerCase()}`;
  const labels = domain.split('.');
  if (labels.length < 2 || labels.some((label) => !domainLabel.test(label))) {
    throw new Error(t('service.validation.routeInvalid', { route }));
  }

  return domain;
}

export function normalizeServiceUrl(url: string): string {
  let parsed: URL;
  try {
    parsed = new URL(url.trim());
  } catch {
    throw new Error(t('service.validation.urlFormat'));
  }

  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') {
    throw new Error(t('service.validation.urlProtocol'));
  }
  if (!parsed.hostname) {
    throw new Error(t('service.validation.urlHostRequired'));
  }
  if (parsed.pathname !== '/' || parsed.search || parsed.hash) {
    throw new Error(t('service.validation.urlNoPath'));
  }

  return parsed.port ? `${parsed.protocol}//${parsed.hostname}:${parsed.port}` : `${parsed.protocol}//${parsed.hostname}`;
}

function normalizeLoopbackHost(hostname: string): string {
  return hostname.replace(/^\[(.*)\]$/, '$1').toLowerCase();
}

export function isContainerLoopbackUrl(url: string): boolean {
  const parsed = new URL(url);
  return ['localhost', '127.0.0.1', '::1'].includes(normalizeLoopbackHost(parsed.hostname));
}

export function replaceServiceUrlHost(url: string, nextHost: string): string {
  const parsed = new URL(url);
  parsed.hostname = nextHost;
  return parsed.port ? `${parsed.protocol}//${parsed.hostname}:${parsed.port}` : `${parsed.protocol}//${parsed.hostname}`;
}

export function serviceDynamicConfigFile(projectDir: string, serviceName: string): string {
  return path.join(projectDir, 'configuration', 'services', `${serviceName}.service.yml`);
}

export function buildServiceDynamicConfig(service: RunestoneServiceRecord, entrypointName: string): string {
  return [
    MANAGED_CONFIG_MARKER,
    'http:',
    '  routers:',
    `    ${service.name}:`,
    `      entryPoints: ${entrypointName}`,
    `      rule: Host(\`${service.route}\`)`,
    `      service: ${service.name}`,
    '      tls: true',
    '  services:',
    `    ${service.name}:`,
    '      loadBalancer:',
    '        servers:',
    `          - url: "${service.url}"`,
    ''
  ].join('\n');
}

export function writeServiceDynamicConfig(config: RunestoneEnv, service: RunestoneServiceRecord): void {
  const filePath = serviceDynamicConfigFile(config.PROJECT_DIR, service.name);
  writeDynamicConfigFile(
    filePath,
    buildServiceDynamicConfig(service, config.WEB_SECURE_ENTRYPOINT_NAME),
    { composeFilePath: config.COMPOSE_FILE_PATH }
  );
}

export function removeServiceDynamicConfig(config: RunestoneEnv, serviceName: string): boolean {
  return removeDynamicConfigFile(
    serviceDynamicConfigFile(config.PROJECT_DIR, serviceName),
    { composeFilePath: config.COMPOSE_FILE_PATH }
  );
}

export function serviceDynamicConfigExists(config: RunestoneEnv, serviceName: string): boolean {
  return fs.existsSync(serviceDynamicConfigFile(config.PROJECT_DIR, serviceName));
}

export function isManagedServiceDynamicConfig(config: RunestoneEnv, serviceName: string): boolean {
  const filePath = serviceDynamicConfigFile(config.PROJECT_DIR, serviceName);
  if (!fs.existsSync(filePath)) {
    return false;
  }

  return fs.readFileSync(filePath, 'utf8').includes(MANAGED_CONFIG_MARKER);
}

function exactHostRule(domain: string): RegExp {
  const escaped = domain.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`Host\\(\\s*[\`"]${escaped}[\`"]\\s*\\)`, 'i');
}

export function assertTraefikAvailability(snapshot: TraefikSnapshot): void {
  if (!snapshot) {
    throw new Error(t('service.traefik.unavailable'));
  }
}

export function assertNoTraefikNameConflict(name: string, snapshot: TraefikSnapshot): void {
  const conflicts: TraefikNameConflict[] = [
    ...snapshot.routers
      .filter((item) => providerBaseName(item.name) === name)
      .map((item) => ({ name: item.name, provider: providerName(item.name), kind: 'router' as const })),
    ...snapshot.services
      .filter((item) => providerBaseName(item.name) === name)
      .map((item) => ({ name: item.name, provider: providerName(item.name), kind: 'service' as const }))
  ];
  if (conflicts.length > 0) {
    const summary = conflicts.map((conflict) => `${conflict.kind} ${conflict.name} (${conflict.provider} provider)`).join(', ');
    throw new Error(t('service.traefik.nameConflict', { name, summary }));
  }
}

export function assertNoTraefikHostConflict(route: string, snapshot: TraefikSnapshot): void {
  const conflict = snapshot.routers.find((router) => router.rule && exactHostRule(route).test(router.rule));
  if (conflict) {
    throw new Error(t('service.traefik.hostConflict', { route, name: conflict.name, provider: providerName(conflict.name) }));
  }
}

export function prepareServiceInput(input: ServiceInput, config: RunestoneEnv): RunestoneServiceRecord {
  return {
    name: validateServiceName(input.name),
    route: normalizeRouteDomain(input.route, config.HOST_DOMAIN),
    url: normalizeServiceUrl(input.url),
    group: validateGroupName(input.group)
  };
}

export function serviceExists(name: string): boolean {
  return toolState.readServices().some((service) => service.name === name);
}

export function addServiceRecord(service: RunestoneServiceRecord): void {
  const services = toolState.readServices();
  if (services.some((item) => item.name === service.name)) {
    throw new Error(t('service.error.existsUseModify', { name: service.name }));
  }

  toolState.writeServices([...services, service].sort((left, right) => left.name.localeCompare(right.name)));
}

export function updateServiceRecord(service: RunestoneServiceRecord): void {
  const services = toolState.readServices();
  if (!services.some((item) => item.name === service.name)) {
    throw new Error(t('service.error.notFound', { name: service.name }));
  }

  toolState.writeServices(services.map((item) => (item.name === service.name ? service : item)));
}

export function removeServiceRecord(name: string): RunestoneServiceRecord {
  const services = toolState.readServices();
  const service = services.find((item) => item.name === name);
  if (!service) {
    throw new Error(t('service.error.notFound', { name }));
  }

  toolState.writeServices(services.filter((item) => item.name !== name));
  return service;
}

export function listServices(config: RunestoneEnv): ServiceListItem[] {
  return toolState.readServices()
    .slice()
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((service) => ({
      ...service,
      dynamicConfigExists: fs.existsSync(serviceDynamicConfigFile(config.PROJECT_DIR, service.name))
    }));
}

function wildcardCoversDomain(san: string, domain: string): boolean {
  const wildcard = san.trim().toLowerCase();
  const normalized = domain.toLowerCase();
  if (!wildcard.startsWith('*.')) {
    return wildcard === normalized;
  }

  const suffix = wildcard.slice(2);
  if (!normalized.endsWith(`.${suffix}`)) {
    return false;
  }

  const prefix = normalized.slice(0, -suffix.length - 1);
  return Boolean(prefix) && !prefix.includes('.');
}

export function findCoveringCertificate(domain: string, certificates: CertificateListItem[]): CertificateListItem | undefined {
  return certificates.find((certificate) => certificate.status === '✓' && certificate.sans.some((san) => wildcardCoversDomain(san, domain)));
}

export function certificateBaseDomainForRoute(domain: string): string {
  const labels = domain.split('.');
  const base = labels.slice(1).join('.');
  if (base.split('.').length < 2) {
    throw new Error(t('service.certificate.routeTooShort', { route: domain }));
  }

  return base;
}

export async function ensureCertificateCoverage(
  config: RunestoneEnv,
  domain: string,
  shouldCreate: () => Promise<boolean>
): Promise<void> {
  const existing = findCoveringCertificate(domain, listDomainCertificates(config.PROJECT_DIR));
  if (existing) {
    return;
  }

  if (!(await shouldCreate())) {
    throw new Error(t('service.certificate.noneCovers', { route: domain }));
  }

  await createDomainCertificate(
    config.PROJECT_DIR,
    certificateBaseDomainForRoute(domain),
    { composeFilePath: config.COMPOSE_FILE_PATH }
  );
}
