import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { load } from 'js-yaml';
import {
  buildDnsUiConfig,
  dnsContainerName,
  dnsUiConfigFile,
  dnsUiHost,
  dnsUiUrl,
  syncDnsUiRoute
} from '../../../src/services/dns/ui-route';
import { testEnv } from '../../helpers/env';

jest.mock('../../../src/services/docker-compose', () => ({
  ...jest.requireActual('../../../src/services/docker-compose'),
  composeService: {
    ps: jest.fn(() => []),
    restart: jest.fn()
  }
}));

interface DynamicConfig {
  http: {
    routers: Record<string, { entryPoints: string; rule: string; service: string; tls: boolean }>;
    services: Record<string, { loadBalancer: { servers: Array<{ url: string }> } }>;
  };
}

describe('dns web UI route (spec 8.5)', () => {
  it('routes the prefixed dns host to webproc inside the dns container', () => {
    const config = testEnv('/tmp/runestone', { HOST_DOMAIN: 'example.test', PREFIX: 'stone' });

    expect(dnsUiHost(config)).toBe('dns.example.test');
    expect(dnsUiUrl(config)).toBe('https://dns.example.test');
    expect(dnsContainerName(config)).toBe('stone-dns');
  });

  it('generates a dynamic configuration Traefik can parse', () => {
    const config = testEnv('/tmp/runestone', { HOST_DOMAIN: 'example.test', PREFIX: 'stone' });

    const parsed = load(buildDnsUiConfig(config)) as DynamicConfig;

    expect(parsed.http.routers['dns-ui']).toEqual({
      entryPoints: 'websecure',
      rule: 'Host(`dns.example.test`)',
      service: 'dns-ui',
      tls: true
    });
    expect(parsed.http.services['dns-ui'].loadBalancer.servers).toEqual([{ url: 'http://stone-dns:8080' }]);
  });

  it('marks the file as generated, so nothing mistakes it for a hand-written route', () => {
    expect(buildDnsUiConfig(testEnv('/tmp/runestone'))).toContain('# Generated by runestone dns.');
  });

  describe('syncDnsUiRoute', () => {
    let projectDir: string;

    beforeEach(() => {
      projectDir = fs.mkdtempSync(path.join(os.tmpdir(), 'runestone-dns-ui-'));
    });

    afterEach(() => {
      fs.rmSync(projectDir, { recursive: true, force: true });
    });

    function config(overrides: Record<string, string> = {}) {
      return testEnv(projectDir, { DNS_ENABLE: 'true', HOST_DOMAIN: 'example.test', ...overrides });
    }

    it('writes the route when DNS and its UI are both on', () => {
      expect(syncDnsUiRoute(config())).toBe(true);
      expect(fs.readFileSync(dnsUiConfigFile(projectDir), 'utf8')).toBe(buildDnsUiConfig(config()));
    });

    it('reports no change on a second identical run', () => {
      syncDnsUiRoute(config());

      expect(syncDnsUiRoute(config())).toBe(false);
    });

    it('removes the route when the UI is turned off', () => {
      syncDnsUiRoute(config());

      expect(syncDnsUiRoute(config({ DNS_UI_ENABLE: 'false' }))).toBe(true);
      expect(fs.existsSync(dnsUiConfigFile(projectDir))).toBe(false);
    });

    it('removes the route when DNS itself is turned off', () => {
      syncDnsUiRoute(config());

      expect(syncDnsUiRoute(config({ DNS_ENABLE: 'false' }))).toBe(true);
      expect(fs.existsSync(dnsUiConfigFile(projectDir))).toBe(false);
    });

    it('does nothing at all when DNS is off and no route was ever written', () => {
      expect(syncDnsUiRoute(config({ DNS_ENABLE: 'false' }))).toBe(false);
      expect(fs.existsSync(path.join(projectDir, 'configuration', 'dns'))).toBe(false);
    });
  });
});
