#!/bin/sh
# runestone-dns entrypoint.
#
# Two of the three configuration files are Runestone's and are regenerated here
# on every container start; they exist only inside the container, so the user
# cannot reach them and whatever this script produces is the authoritative
# version. The third, custom.conf, belongs to the user and is never overwritten.
# See docs/DNS-FEATURE-SPEC.md section 8.3.
#
# The consequence worth stating: if the container starts, the configuration is
# correct — with no dependency on whether the CLI was ever run. That is what
# makes `restart: unless-stopped` bringing this container back after a host
# reboot safe without any CLI involvement.
set -eu

DNSMASQ_CONF=/etc/dnsmasq.conf
MANAGED_CONF=/etc/dnsmasq.d/managed.conf
CUSTOM_CONF=/etc/dnsmasq.d/custom.conf

SSL_DIR=${SSL_DIR:-/ssl}
DNS_UI_PORT=${DNS_UI_PORT:-8080}
DNS_HOST_IP=${DNS_HOST_IP:-}
DNS_UPSTREAM=${DNS_UPSTREAM:-}

# The CLI guarantees a non-empty upstream list (spec 8.4). The image still
# refuses to run without one, because dnsmasq is started with no-resolv: an
# empty list would leave every container on the machine unable to resolve
# anything that is not a Runestone domain.
FALLBACK_UPSTREAM=1.1.1.1

log() {
    echo "runestone-dns: $*"
}

fail() {
    echo "runestone-dns: $*" >&2
    exit 1
}

require_host_ip() {
    [ -n "$DNS_HOST_IP" ] || fail \
        "DNS_HOST_IP is not set. It is the address Runestone domains must resolve to, so without it this container would start and answer nothing useful."
}

resolve_upstream() {
    if [ -z "$DNS_UPSTREAM" ]; then
        log "DNS_UPSTREAM is empty; falling back to ${FALLBACK_UPSTREAM}. Every non-Runestone lookup from every container on this machine will go there."
        DNS_UPSTREAM=$FALLBACK_UPSTREAM
    fi
}

# Mirrors the CLI's own domain rule (normalizeDomain): at least two labels, each
# of alphanumerics and hyphens, and no leading or trailing hyphen.
is_valid_domain() {
    printf '%s' "$1" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'
}

ensure_custom_conf() {
    if [ -d "$CUSTOM_CONF" ]; then
        fail "$CUSTOM_CONF is a directory. Docker creates a directory when a bind-mounted file does not exist on the host, so create the file before starting this service."
    fi

    [ -f "$CUSTOM_CONF" ] && return 0

    log "creating an empty $CUSTOM_CONF"
    cat > "$CUSTOM_CONF" <<'EOF'
# Your own dnsmasq rules. Runestone never overwrites this file.
#
# Examples:
#   address=/example.test/127.0.0.1     the domain and all of its subdomains
#   server=/internal.example/10.0.0.53  forward one zone to a specific resolver
#   strict-order                        try upstreams in the listed order rather
#                                       than favouring whichever answers fastest
EOF
}

generate_dnsmasq_conf() {
    {
        echo "# Generated by runestone-dns on every container start. Do not edit."
        echo "# This file exists only inside the container and is overwritten at each start."
        echo
        echo "# Forward only to the servers Runestone was given, never to a resolver"
        echo "# inherited from the container's own /etc/resolv.conf, which on this"
        echo "# machine may well be this very container."
        echo "no-resolv"
        echo

        old_ifs=$IFS
        IFS=','
        for upstream in $DNS_UPSTREAM; do
            trimmed=$(printf '%s' "$upstream" | tr -d '[:space:]')
            [ -n "$trimmed" ] || continue
            echo "server=$trimmed"
        done
        IFS=$old_ifs

        echo
        echo "conf-file=$MANAGED_CONF"
        echo "conf-file=$CUSTOM_CONF"
    } > "$DNSMASQ_CONF"
}

generate_managed_conf() {
    mapped=0
    skipped=0

    {
        echo "# Generated by runestone-dns on every container start. Do not edit."
        echo "# One entry per certificate in $SSL_DIR. address=/domain/ip covers the"
        echo "# domain and all of its subdomains."
        echo
    } > "$MANAGED_CONF"

    if [ ! -d "$SSL_DIR" ]; then
        log "$SSL_DIR is not mounted; no Runestone domains will be answered"
        return 0
    fi

    for certificate in "$SSL_DIR"/*.crt; do
        [ -e "$certificate" ] || continue

        name=$(basename "$certificate" .crt)
        if [ "$name" = "rootCA" ]; then
            continue
        fi

        domain=$(printf '%s' "$name" | tr '[:upper:]' '[:lower:]')
        if is_valid_domain "$domain"; then
            printf 'address=/%s/%s\n' "$domain" "$DNS_HOST_IP" >> "$MANAGED_CONF"
            mapped=$((mapped + 1))
        else
            log "skipping '$(basename "$certificate")': '$domain' is not a valid domain name"
            skipped=$((skipped + 1))
        fi
    done

    log "mapped $mapped domain(s) to $DNS_HOST_IP, skipped $skipped"
}

ensure_custom_conf
require_host_ip
resolve_upstream
generate_dnsmasq_conf
generate_managed_conf

# Any explicit command replaces the service, so that the generated configuration
# can be inspected with `docker run ... cat /etc/dnsmasq.conf`.
if [ "$#" -gt 0 ]; then
    exec "$@"
fi

if [ -z "${HTTP_USER:-}${HTTP_PASS:-}" ]; then
    log "the web UI has no authentication: anyone who can reach it may change custom DNS rules"
fi

# Confirmed against webproc 0.4.0: the writable-configuration flag is
# --configuration-file (-c), not --config. --restart-watch additionally restarts
# dnsmasq when custom.conf changes on disk, which covers the user editing their
# own file with an editor rather than through the UI.
#
# HTTP_USER and HTTP_PASS are deliberately *not* passed as flags: webproc reads
# both from the environment, and a password given on the command line would show
# up in the container's process list.
log "starting dnsmasq (webproc ${WEBPROC_VERSION:-unknown} watching $CUSTOM_CONF)"
exec webproc \
    --configuration-file "$CUSTOM_CONF" \
    --port "$DNS_UI_PORT" \
    --restart-watch \
    -- dnsmasq --no-daemon --conf-file="$DNSMASQ_CONF" --log-facility=-
