import * as path from 'path';
import { RunestoneEnv } from '../../utils/env-loader';
import { removeDynamicConfigFile, writeDynamicConfigFile } from '../dynamic-config-manager';
import { isDnsEnabled, isDnsUiEnabled } from './settings';

/**
 * The Traefik route for webproc's UI (spec 8.5).
 *
 * The route is generated by the CLI rather than templated into the runestone
 * image, so that enabling or disabling the UI needs no new image. Commit
 * `3581211` put `{{ if env "DNS_ENABLE" }}` blocks in the image's dynamic
 * template instead; those are removed (spec 13).
 */

const MANAGED_CONFIG_MARKER = '# Generated by runestone dns.';

export function dnsUiConfigFile(projectDir: string): string {
  return path.join(projectDir, 'configuration', 'dns', 'dns-ui.yml');
}

export function dnsContainerName(config: Pick<RunestoneEnv, 'PREFIX'>): string {
  return `${config.PREFIX}-dns`;
}

export function dnsUiHost(config: Pick<RunestoneEnv, 'HOST_DOMAIN'>): string {
  return `dns.${config.HOST_DOMAIN}`;
}

export function dnsUiUrl(config: Pick<RunestoneEnv, 'HOST_DOMAIN'>): string {
  return `https://${dnsUiHost(config)}`;
}

export function buildDnsUiConfig(
  config: Pick<RunestoneEnv, 'HOST_DOMAIN' | 'PREFIX' | 'WEB_SECURE_ENTRYPOINT_NAME'>
): string {
  return [
    MANAGED_CONFIG_MARKER,
    'http:',
    '  routers:',
    '    dns-ui:',
    `      entryPoints: ${config.WEB_SECURE_ENTRYPOINT_NAME}`,
    `      rule: Host(\`${dnsUiHost(config)}\`)`,
    '      service: dns-ui',
    '      tls: true',
    '  services:',
    '    dns-ui:',
    '      loadBalancer:',
    '        servers:',
    `          - url: "http://${dnsContainerName(config)}:8080"`,
    ''
  ].join('\n');
}

/**
 * Writes the route when DNS and its UI are both on, removes it otherwise.
 * Returns whether anything changed, which is what triggers a service-scoped
 * restart of `runestone` so Traefik reloads.
 */
export function syncDnsUiRoute(config: RunestoneEnv): boolean {
  const filePath = dnsUiConfigFile(config.PROJECT_DIR);
  const runtime = { composeFilePath: config.COMPOSE_FILE_PATH };

  if (isDnsEnabled(config) && isDnsUiEnabled(config)) {
    return writeDynamicConfigFile(filePath, buildDnsUiConfig(config), runtime);
  }

  return removeDynamicConfigFile(filePath, runtime);
}
