import * as fs from 'fs';
import * as path from 'path';
import { DEFAULT_ENV, EnvInput, RunestoneEnv, envLoader } from './env-loader';
import { pathHelpers } from './path-helpers';

/**
 * Bumped whenever `buildComposeFile()` changes in a way existing installations
 * need. The Compose file used to be written only when absent, so an upgrading
 * user would never have received a newly added service (spec 13).
 *
 * 1  the pre-DNS template (never carried a marker; an absent marker means this)
 * 2  adds the dns service under profile `dns`
 */
export const COMPOSE_TEMPLATE_VERSION = '3';

const COMPOSE_MARKER_PREFIX = '# runestone-compose-template:';
const COMPOSE_MARKER_PATTERN = /^# runestone-compose-template:\s*(\S+)/m;

/**
 * The version is recorded in the Compose file's own header rather than in `.env`.
 * `.env` would have meant rewriting the user's environment file — which drops
 * their comments, because it is regenerated from parsed key-value pairs — on an
 * ordinary `up`. A header travels with the file it describes, is per-project, and
 * cannot drift from it.
 */
export function readComposeTemplateVersion(composeText: string): string {
  const match = COMPOSE_MARKER_PATTERN.exec(composeText);
  return match ? match[1] : '';
}

export function buildComposeFile(): string {
  return `${COMPOSE_MARKER_PREFIX} ${COMPOSE_TEMPLATE_VERSION}
# Generated by Runestone. When the template version above changes, this file is
# regenerated; anything you changed here is kept in a .bak file beside it.
services:
  runestone:
    image: \${RUNESTONE_IMAGE:-cymondez/runestone}:\${RUNESTONE_TAG:-5.2}
    container_name: \${PREFIX:-runestone}
    restart: unless-stopped
    command: |-
      --providers.docker.network="\${PREFIX:-runestone}-network"
    environment:
      HOST_DOMAIN: \${HOST_DOMAIN:-local.developers-homelab.net}
      MAILPIT_HOST: mailpit.\${HOST_DOMAIN:-local.developers-homelab.net}
      TRAEFIK_HOST: traefik.\${HOST_DOMAIN:-local.developers-homelab.net}
      WEB_ENTRYPOINT_NAME: \${WEB_ENTRYPOINT_NAME:-web}
      WEB_ENTRYPOINT_PORT: \${WEB_ENTRYPOINT_PORT:-80}
      WEB_SECURE_ENTRYPOINT_NAME: \${WEB_SECURE_ENTRYPOINT_NAME:-websecure}
      WEB_SECURE_ENTRYPOINT_PORT: \${WEB_SECURE_ENTRYPOINT_PORT:-443}
      PREFIX: \${PREFIX:-runestone}
    ports:
      - "\${WEB_ENTRYPOINT_PORT:-80}:\${WEB_ENTRYPOINT_PORT:-80}"
      - "\${WEB_SECURE_ENTRYPOINT_PORT:-443}:\${WEB_SECURE_ENTRYPOINT_PORT:-443}"
      - "\${SMTP_PORT:-1025}:1025"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/ssl
      - ./configuration:/configuration
      - ssh:/tmp/druid_ssh-agent/

  dns:
    image: cymondez/runestone-dns:1.0
    container_name: \${PREFIX:-runestone}-dns
    restart: unless-stopped
    profiles:
      - dns
    ports:
      - "\${DNS_BIND_PREFIX:-}53:53/tcp"
      - "\${DNS_BIND_PREFIX:-}53:53/udp"
    environment:
      DNS_HOST_IP: \${DNS_HOST_IP:-}
      DNS_UPSTREAM: \${DNS_UPSTREAM:-1.1.1.1}
      HTTP_USER: \${DNS_UI_USER:-}
      HTTP_PASS: \${DNS_UI_PASS:-}
    dns:
      - \${DNS_CONTAINER_RESOLVER:-1.1.1.1}
    volumes:
      - ./certs:/ssl:ro
      - ./dns/custom.conf:/etc/dnsmasq.d/custom.conf

networks:
  default:
    name: \${PREFIX:-runestone}-network
    external: true

volumes:
  ssh:
    name: \${PREFIX:-runestone}-ssh
    external: true
`;
}

export function defaultEnvInput(): EnvInput {
  return { ...DEFAULT_ENV };
}

/**
 * The dnsmasq rules the user owns. Runestone creates this file when it is
 * missing and **never overwrites it** (spec 8.3). It has to exist before the dns
 * service starts, because Docker creates a *directory* where a bind-mounted file
 * does not exist.
 *
 * It lives under `dns/`, never under `configuration/`: Traefik's file provider
 * reads `/configuration` recursively, so a `.conf` file there would produce
 * parse errors and log noise (spec 7.2).
 */
export function dnsCustomConfPath(projectDir: string): string {
  return path.join(projectDir, 'dns', 'custom.conf');
}

export function buildDnsCustomConf(): string {
  return [
    '# Your own dnsmasq rules. Runestone never overwrites this file.',
    '#',
    '# Examples:',
    '#   address=/example.test/127.0.0.1     the domain and all of its subdomains',
    '#   server=/internal.example/10.0.0.53  forward one zone to a specific resolver',
    '#   strict-order                        try upstreams in the listed order rather',
    '#                                       than favouring whichever answers fastest',
    ''
  ].join('\n');
}

function nextBackupPath(filePath: string): string {
  let candidate = `${filePath}.bak`;
  let counter = 2;
  while (fs.existsSync(candidate)) {
    candidate = `${filePath}.bak${counter}`;
    counter += 1;
  }

  return candidate;
}

export interface ComposeFileUpdate {
  written: boolean;
  /** Set when an existing file was kept aside rather than discarded. */
  backupPath?: string;
  /** Template version the file on disk carried; empty means it carried none. */
  fromVersion: string;
  toVersion: string;
}

function updateComposeFile(config: RunestoneEnv, force: boolean): ComposeFileUpdate {
  const desired = buildComposeFile();
  const unchanged: ComposeFileUpdate = {
    written: false,
    fromVersion: COMPOSE_TEMPLATE_VERSION,
    toVersion: COMPOSE_TEMPLATE_VERSION
  };

  if (!fs.existsSync(config.COMPOSE_FILE_PATH)) {
    fs.writeFileSync(config.COMPOSE_FILE_PATH, desired, 'utf8');
    return { written: true, fromVersion: '', toVersion: COMPOSE_TEMPLATE_VERSION };
  }

  const existing = fs.readFileSync(config.COMPOSE_FILE_PATH, 'utf8');
  const fromVersion = readComposeTemplateVersion(existing);

  if (!force && fromVersion === COMPOSE_TEMPLATE_VERSION) {
    return unchanged;
  }

  if (existing === desired) {
    return { written: false, fromVersion, toVersion: COMPOSE_TEMPLATE_VERSION };
  }

  // Runestone cannot tell an older template's output from something the user
  // edited, so it keeps the file either way rather than deciding which of the
  // two it is looking at.
  const backupPath = nextBackupPath(config.COMPOSE_FILE_PATH);
  fs.copyFileSync(config.COMPOSE_FILE_PATH, backupPath);
  fs.writeFileSync(config.COMPOSE_FILE_PATH, desired, 'utf8');

  return { written: true, backupPath, fromVersion, toVersion: COMPOSE_TEMPLATE_VERSION };
}

export function ensureProjectFiles(config: RunestoneEnv, options?: { overwriteCompose?: boolean }): ComposeFileUpdate {
  pathHelpers.ensureDir(config.PROJECT_DIR);
  pathHelpers.ensureDir(path.join(config.PROJECT_DIR, 'certs'));
  pathHelpers.ensureDir(path.join(config.PROJECT_DIR, 'configuration'));
  pathHelpers.ensureDir(path.join(config.PROJECT_DIR, 'configuration', 'certs'));
  pathHelpers.ensureDir(path.join(config.PROJECT_DIR, 'configuration', 'services'));
  pathHelpers.ensureDir(path.join(config.PROJECT_DIR, 'dns'));

  if (!fs.existsSync(config.ENV_PATH)) {
    envLoader.write(config.ENV_PATH, defaultEnvInput());
  }

  const customConf = dnsCustomConfPath(config.PROJECT_DIR);
  if (!fs.existsSync(customConf)) {
    fs.writeFileSync(customConf, buildDnsCustomConf(), 'utf8');
  }

  return updateComposeFile(config, options?.overwriteCompose === true);
}
